import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

// Load Montserrat from Google Fonts
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <head>
        {/* Load Satoshi from Fontshare */}
        <link
          rel="stylesheet"
          href="https://api.fontshare.com/css?f[]=satoshi@400,500,700&display=swap"
        />
      </head>
      <body className="font-satoshi antialiased">{children}</body>
    </html>
  );
}
